### ISSUE TITLE
Activate extension on other file types

### ISSUE THREAD

**Issue by wongjn** [wongjn/vscode-php-sniffer#16]
**Is your feature request related to a problem? Please describe.**
Some standards validate other file types, such as CSS, JS, markdown but the extension in its current state only activates for PHP files.

**Describe the solution you'd like**
Add a setting to run the extension on other file types.

**Additional context**
The drupal/coder standards checks on markdown as well as .info files for example.

**Comment by drholera** [comment]
I need it too, for the moment it doesn't work for .module or .theme file in Drupal.

**Comment by wongjn** [comment]
Since those are PHP files, you can add this to your vscode settings to get this extension (and other PHP extensions) to work:

```json
"files.associations": {
  "*.theme": "php",
  "*.module": "php",
  "*.profile": "php",
  "*.inc": "php",
  "*.install": "php"
}
```

**Comment by drholera** [comment]
Great, thanks for your help!

**Comment by nkoporec** [comment]
The file associations do not work with phpcs, because the phpcs by default only works with certain file types, if you want to scan other file types then you must add the --extensions argument to the CLI command, see https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#specifying-valid-file-extensions

It would be useful if there would be an additional setting that would allow you to pass in the extensions, for example: `"phpSniffer.extensions": [ "engine", "inc", "install", "make", "module", "profile", "theme", "tpl.php", "test", "php", ]`

**Comment by butlerjraines** [comment]
@nkoporec did you find a resolution to this? I am experiencing the same problem.

**Comment by nkoporec** [comment]
@butlerjraines no, unfortunalty, I have migrated from vscode to vim in the meantime.

**Comment by wongjn** [comment]
@nkoporec @butlerjraines One can add extensions argument into a ruleset `xml` file to do the equivalent of the `--extensions` argument as a work-around until this gets feature is developed into this extension:
```xml
<arg name="extensions" value="php,inc,theme" />
```
This should work along with [these settings mentioned above](#issuecomment-633528824).
