### ISSUE TITLE
Autodetect phpcs as project dependency and phpcs.xml.dist or phpcs.xml

### ISSUE THREAD

**Issue by elvishp2006** [wongjn/vscode-php-sniffer#5]
This is only a feature request. Will be great if the extension auto detect these files and maybe auto detect if I'm using the phpcs as a project dependency.

**Comment by valeryan** [comment]
@wongjn I have the support for autoconfig search built into my extension for phpcbf and I really like how you handle running phpcs.  So I created a new extension that combines how I run phpcbf with how you run phpcs. found here: https://github.com/valeryan/vscode-phpsab. I would just use yours but my phpcbf extension is used by my team and is an integral part of our workflow. The autoconfig search is a must for our team because we handle lots of extension development for MediaWiki and as such the coding standards can change from folder to folder. Anyway, It provides a pretty good example of how to handle the autoconfig search stuff. Maybe it will be useful to you.
